In [5]:
import pandas as pd
df = pd.read_csv("sequoiaGE.csv", sep=';', low_memory=False)

In [6]:
df.shape

(238789, 23)

In [7]:
df.head()

,OBJECTID,ID_NOM,ID_TAXON,ID_ARBRE,CLASSE,NOM_LATIN,NOM_COM_GE,NOM_COMMUN,NOM_COM_RE,DIAM_1M,...,CHAMPION,INT_PHENO,STATUT,ADR_URL,COMMUNE,NO_POSTAL,CIRCONFERENCE,DATE_OBSERVATION,E,N
0,114,10481,24954,172763,Conifères,Pinus,Pin,Pin,Pin,NaN,...,0,NaN,Historique,https://www.patrimoine-vert-geneve.ch/arbres/a...,Thônex,1226,NaN,19760606.0,2503917.62,1115677.60
1,115,10837,26178,137146,Feuillus,Populus,Peuplier,Peuplier,Peuplier,NaN,...,0,NaN,Historique,https://www.patrimoine-vert-geneve.ch/arbres/a...,Chêne-Bougeries,1224,NaN,19760606.0,2502747.22,1117416.76
2,116,10481,24954,137147,Conifères,Pinus,Pin,Pin,Pin,NaN,...,0,NaN,Historique,https://www.patrimoine-vert-geneve.ch/arbres/a...,Chêne-Bougeries,1224,NaN,19760606.0,2502711.81,1117427.18
3,117,14788,38896,138208,Conifères,Taxus,If,If,If,NaN,...,0,NaN,Historique,https://www.patrimoine-vert-geneve.ch/arbres/a...,Genève-Eaux-Vives,1206,NaN,19760606.0,2501802.23,1116316.00
4,118,10481,24954,138212,Conifères,Pinus,Pin,Pin,Pin,NaN,...,0,NaN,Historique,https://www.patrimoine-vert-geneve.ch/arbres/a...,Genève-Eaux-Vives,1206,NaN,19760606.0,2501718.31,1116262.83

In [23]:
sequoia = df[df['NOM_COMMUN'] == 'Séquoia']

In [25]:
sequoia

,OBJECTID,ID_NOM,ID_TAXON,ID_ARBRE,CLASSE,NOM_LATIN,NOM_COM_GE,NOM_COMMUN,NOM_COM_RE,DIAM_1M,...,CHAMPION,INT_PHENO,STATUT,ADR_URL,COMMUNE,NO_POSTAL,CIRCONFERENCE,DATE_OBSERVATION,E,N
250,168,13998,37435,132408,Conifères,Sequoiadendron,Séquoia,Séquoia,"Séquoia, Séquoia géant pleureur",NaN,...,0,NaN,Historique,https://www.patrimoine-vert-geneve.ch/arbres/a...,Satigny,1242,NaN,19760606.0,2491116.83,1118380.98
1560,1480,13998,37435,1540,Conifères,Sequoiadendron,Séquoia,Séquoia,"Séquoia, Séquoia géant pleureur",NaN,...,0,NaN,Historique,https://www.patrimoine-vert-geneve.ch/arbres/a...,Genève-Cité,1201,NaN,19760606.0,2499877.62,1119001.98
1653,1598,13998,37435,3359,Conifères,Sequoiadendron,Séquoia,Séquoia,"Séquoia, Séquoia géant pleureur",NaN,...,0,NaN,Historique,https://www.patrimoine-vert-geneve.ch/arbres/a...,Russin,1281,NaN,19760606.0,2489940.63,1116272.00
1743,1688,13998,37435,2508,Conifères,Sequoiadendron,Séquoia,Séquoia,"Séquoia, Séquoia géant pleureur",NaN,...,0,NaN,Historique,https://www.patrimoine-vert-geneve.ch/arbres/a...,Avully,1237,NaN,19760606.0,2488720.72,1114827.97
1746,1691,13998,37435,2511,Conifères,Sequoiadendron,Séquoia,Séquoia,"Séquoia, Séquoia géant pleureur",NaN,...,0,NaN,Historique,https://www.patrimoine-vert-geneve.ch/arbres/a...,Avully,1237,NaN,19760606.0,2488569.93,1114872.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192677,191168,13993,37420,303376,Conifères,Sequoia,Séquoia,Séquoia,Séquoia,40.0,...,0,NaN,Relevé,pas de fiche,Vandoeuvres,1253,126.0,20140619.0,2504531.14,1120192.23
192678,191169,13993,37420,303377,Conifères,Sequoia,Séquoia,Séquoia,Séquoia,54.0,...,0,NaN,Relevé,pas de fiche,Vandoeuvres,1253,170.0,20140619.0,2504527.72,1120190.17
195251,193335,13993,37420,303536,Conifères,Sequoia,Séquoia,Séquoia,Séquoia,60.0,...,0,NaN,Relevé,pas de fiche,Vandoeuvres,1253,188.0,20140619.0,2504457.61,1120099.36
217296,217879,13998,37435,351062,Conifères,Sequoiadendron,Séquoia,Séquoia,"Séquoia, Séquoia géant pleureur",NaN,...,0,NaN,Relevé,https://www.patrimoine-vert-geneve.ch/arbres/a...,Genève-Petit-Saconnex,1202,105.0,20240816.0,2500561.99,1119790.94
231520,232580,13994,37421,388714,Conifères,Sequoia gigantea,Séquoia,Séquoia,Séquoia,NaN,...,1,NaN,Relevé,NaN,Genève-Eaux-Vives,1207,575.0,20240621.0,2501923.71,1118196.01

In [26]:
sequoia.shape

(259, 23)

In [27]:
sequoia.to_csv('sequoia_list.csv', index=False)